/*
CREATE DATABASE ONG
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
*/

CREATE TABLE IF NOT EXISTS USUARIO (
	ID_USU 					SERIAL,
	CPFCNPJ 				VARCHAR(40),
	NOME 						VARCHAR(100) 	NOT NULL,
	DATANASCIMENTO 	DATE,
	SEXO 						CHAR(1),
	EMAIL 					VARCHAR(50) 	NOT NULL,
	/*USUARIO 			VARCHAR(10),*/
	SENHA 					VARCHAR(50) 	NOT NULL,
	TP_USU 					BOOLEAN 			NOT NULL
);

ALTER TABLE USUARIO
	ADD CONSTRAINT PK_USU
		PRIMARY KEY (ID_USU);

ALTER TABLE USUARIO 
	ADD CONSTRAINT CH_SEXO 
		CHECK(SEXO IN ('M', 'F'));
		
ALTER TABLE USUARIO 
	ADD CONSTRAINT CH_DATANASCIMENTO
		CHECK(DATANASCIMENTO > '1900-01-01');


CREATE TABLE IF NOT EXISTS ENDERECO (
	ID_ENDERENCO 	SERIAL,
	CEP 					VARCHAR(9) 		NOT NULL,
	UF 						CHAR (2) 			NOT NULL,
	CIDADE 				VARCHAR(50) 	NOT NULL,
	BAIRRO 				VARCHAR(50) 	NOT NULL,
	RUA 					VARCHAR(150) 	NOT NULL,
	NUMERO 				VARCHAR(5) 		NOT NULL,
	COMPLEMENTO 	VARCHAR(50)
);

ALTER TABLE ENDERECO
	ADD CONSTRAINT PK_ENDERECO 
		PRIMARY KEY (ID_ENDERENCO);

ALTER TABLE ENDERECO
	ADD CONSTRAINT FK_ENDERECO_CLIENTE 
		FOREIGN KEY (ID_ENDERENCO) 
		REFERENCES USUARIO(ID_USU)
		ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS TELEFONE(
	ID_TELEFONE SERIAL,
	TIPO 				CHAR(1) 		NOT NULL,
	DDD 				CHAR(3) 		NOT NULL,
	FONE 				VARCHAR(9) 	NOT NULL
);

ALTER TABLE TELEFONE
	ADD CONSTRAINT PK_TELEFONE
		PRIMARY KEY (ID_TELEFONE);
		
ALTER TABLE TELEFONE 
	ADD CONSTRAINT CH_TIPO
		CHECK(TIPO IN ('C', 'F'));
		
ALTER TABLE TELEFONE
	ADD CONSTRAINT FK_TELEFONE_CLIENTE 
		FOREIGN KEY (ID_TELEFONE) 
		REFERENCES USUARIO(ID_USU)
		ON DELETE CASCADE;
	
	

CREATE TABLE IF NOT EXISTS ANIMAL (
	ID_ANIMAL 	SERIAL,
	NOME 				VARCHAR(50) 	NOT NULL,
	IDADE 			INT						NOT NULL,
	ESPECIE			VARCHAR(30) 	NOT NULL,
	RACA 				VARCHAR(30) 	NOT NULL,
	PORTE				VARCHAR(30) 	NOT NULL,
	FOTO				VARCHAR(50),
	DESCRICAO		VARCHAR(280),
	ID_USU			INT 					NOT NULL
);

ALTER TABLE ANIMAL
	ADD CONSTRAINT PK_ANIMAL
		PRIMARY KEY (ID_ANIMAL);

ALTER TABLE ANIMAL
	ADD CONSTRAINT FK_ANIMAL_USU
		FOREIGN KEY (ID_USU) 
		REFERENCES USUARIO(ID_USU)
		ON DELETE CASCADE;